apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceb
  labels:
    service: serviceb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: serviceb
  template:
    metadata:
      labels:
        service: serviceb
    spec:
      containers:
      - name: serviceb-container
        image: hhana982/serviceb:1.3
        ports:
        - containerPort: 5000
        env: 
        - name: num
          value: "5"